sakiyamaK/DeclarativeUIKit

- DeclarativeUIKitDemo/DeclarativeUIKitDemo/HotReloadViewController.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/RootViewController.swift
- Sources/DeclarativeUIKit/Helper/HelperTouchTransparencyView.swift
- Sources/DeclarativeUIKit/ViewExtension/UIView+.swift
> center()したら後ろのタッチが反応しなくなる不具合の修正

- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Simple/Simple2ViewController.swift
- Sources/DeclarativeUIKit/ViewExtension/UIControll+.swift
- iOS14から使えるUIActionを使ってボタンタップなどの処理をできるようにしました。
> Add UIAction to Extension of UIControl

- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Simple/SimpleViewController.swift
- Sources/DeclarativeUIKit/ViewExtension/UISwitch+.swift
- UISwitchも使えるようにExtensionを追加しました。
> Add UISwitch extensions

- DeclarativeUIKitDemo/DeclarativeUIKitDemo.xcodeproj/project.pbxproj
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/HotReloadViewController.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Map/MapViewController.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/RootViewController.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Simple/Simple2ViewController.swift
- Documentation/ja/uialertcontroller.md
- Documentation/ja/uicontrol.md
- README.md
- Sources/DeclarativeUIKit/ViewExtension/MKMapView+.swift
- Sources/DeclarativeUIKit/ViewExtension/MKPointAnnotation+.swift
> MKMapVIewを宣言的に対応

- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Simple/Simple2ViewController.swift
- Sources/DeclarativeUIKit/ViewExtension/UIProgressView+.swift
> UIProgressViewを宣言的に対応

- Documentation/ja/index.md
- Documentation/ja/uiview.md
- Sources/DeclarativeUIKit/Helper/ActionHandler.swift
- Sources/DeclarativeUIKit/Helper/HelperCustomSpacingView.swift
- Sources/DeclarativeUIKit/Helper/HelperTouchTransparencyView.swift
- Sources/DeclarativeUIKit/Helper/HelperTouchView.swift
- Sources/DeclarativeUIKit/Helper/HelperUIEdge.swift
- Sources/DeclarativeUIKit/ViewExtension/UIView+.swift
> タッチアクションの宣言的対応

- Sources/DeclarativeUIKit/ViewExtension/UIScrollView+.swift
> 色々なUIScrollViewのパラメータを宣言的に対応

- Sources/DeclarativeUIKit/ViewExtension/UIButton+.swift
> UIButtonのcontentEdgeInsetなどの対応

- Documentation/en/index.md
- Documentation/en/uitextview.md
- Documentation/ja/index.md
- Documentation/ja/uitextview.md
- Sources/DeclarativeUIKit/ViewExtension/UITextView+.swift
> UITextViewを追加

- Documentation/en/index.md
- Documentation/en/uialertcontroller.md
- Documentation/en/uicollectionview.md
- Documentation/en/uigesturerecognizer.md
- Documentation/en/uiimageview.md
- Documentation/en/uilabel.md
- Documentation/en/uiscrollview.md
- Documentation/en/uistackview.md
- Documentation/en/uiswitch.md
- Documentation/en/uitextfield.md
- Documentation/en/uiview.md
- Documentation/ja/index.md
- Documentation/ja/uialertcontroller.md
- Documentation/ja/uibutton.md
- Documentation/ja/uicollectionview.md
- Documentation/ja/uigesturerecognizer.md
- Documentation/ja/uiimageview.md
- Documentation/ja/uilabel.md
- Documentation/ja/uiscrollview.md
- Documentation/ja/uistackview.md
- Documentation/ja/uiswitch.md
- Documentation/ja/uitextfield.md
- Documentation/ja/uiview.md
> ドキュメントのinitializerスペルミス修正

- README.md
> READMEのタイポ

- Sources/DeclarativeUIKit/ViewExtension/UIButton+.swift
> UIButtonのNSAttributedStringも宣言的に対応

- Documentation/en/index.md
- Documentation/en/uitextfield.md
- Documentation/en/uitextview.md
- Documentation/ja/index.md
- Documentation/ja/uitextfield.md
- Documentation/ja/uitextview.md
- Sources/DeclarativeUIKit/ViewExtension/UITextField+.swift
- Sources/DeclarativeUIKit/ViewExtension/UITextView+.swift
> UITextInputTraitsのパラメータに対応

- DeclarativeUIKitDemo/DeclarativeUIKitDemo.xcodeproj/project.pbxproj
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Simple/Simple2ViewController.swift
- Sources/DeclarativeUIKit/ViewExtension/UIImageView+.swift
> fix uiimageview.tintcolor

- Documentation/en/index.md
- Documentation/en/uibarbuttonitem.md
- Documentation/en/uibaritem.md
- Documentation/en/uiviewcontroller.md
- Documentation/ja/index.md
- Documentation/ja/uibarbuttonitem.md
- Documentation/ja/uibaritem.md
- Documentation/ja/uiviewcontroller.md
- Sources/DeclarativeUIKit/ControllerExtension/UIViewController+.swift
- Sources/DeclarativeUIKit/ViewExtension/UIBarButtonItem+.swift
- Sources/DeclarativeUIKit/ViewExtension/UIBarItem+.swift
> UIBarButtonItemを宣言的に書けるように修正

- Documentation/en/index.md
- Documentation/en/uibutton.md
- Documentation/en/uibuttonconfiguration.md
- Documentation/ja/index.md
- Documentation/ja/uibutton.md
- Documentation/ja/uibuttonconfiguration.md
- Sources/DeclarativeUIKit/Helper/Applyable.swift
- Sources/DeclarativeUIKit/OtherExtension/UIButton.Configuration+.swift
- Sources/DeclarativeUIKit/ViewExtension/UIButton+.swift
> Feature/UI button.configuration

- Documentation/en/index.md
- Documentation/en/uicollectionlayoutlistconfiguration.md
- Documentation/en/uicontextualaction.md
- Documentation/en/uiswipeactionsconfiguration.md
- Documentation/ja/index.md
- Documentation/ja/uicollectionlayoutlistconfiguration.md
- Documentation/ja/uicontextualaction.md
- Documentation/ja/uiswipeactionsconfiguration.md
- Sources/DeclarativeUIKit/OtherExtension/UICollectionLayoutListConfiguration+.swift
- Sources/DeclarativeUIKit/OtherExtension/UIContextualAction+.swift
- Sources/DeclarativeUIKit/OtherExtension/UISwipeActionsConfiguration+.swift
> UICollectionViewCompositionalLayout.list周りの設定を宣言的にやれるように修正

- Sources/DeclarativeUIKit/ControllerExtension/UIViewController+.swift
- Sources/DeclarativeUIKit/Helper/UIEdgeLayoutGuide.swift
- Sources/DeclarativeUIKit/ViewExtension/UIView+.swift
> safeAreaLayoutGuide

- DeclarativeUIKitDemo/DeclarativeUIKitDemo.xcodeproj/project.pbxproj
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Actor/ActorViewController.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/CopyAppleSwiftUITutorial/Model/ModelData.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/CopyAppleSwiftUITutorial/View/LandmarkDetail/LandmarkDetailViewController.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/CopyAppleSwiftUITutorial/View/LandmarkList/LandmarkListViewController.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/CopyAppleSwiftUITutorial/View/LandmarkList/LandmarkRow.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/CopyAppleSwiftUITutorial/View/LandmarkList/ToggleRow.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Github/GithubAPI.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Github/GithubResultWeb/GithubResultWebPresenter.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Github/GithubResultWeb/GithubResultWebViewContrller.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Github/GithubSearch/GithubSearchCollectionViewCell.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Github/GithubSearch/GithubSearchCollectionViewController.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Github/GithubSearch/GithubSearchPresenter.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/RootViewController.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Simple/Simple2ViewController.swift
- Sources/DeclarativeUIKit/ControllerExtension/UIViewController+.swift
- Sources/DeclarativeUIKit/ViewExtension/UIScrollView+.swift
- Sources/DeclarativeUIKit/ViewExtension/UIStackView+.swift
> swift6対応でActorでも使えるようにした

- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Picker/PickerViewController.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/RootViewController.swift
- Documentation/en/index.md
- Documentation/en/uidatepicker.md
- Documentation/en/uipickerview.md
- Documentation/ja/index.md
- Documentation/ja/uidatepicker.md
- Documentation/ja/uipickerview.md
- Sources/DeclarativeUIKit/ViewExtension/UIDatePicker+.swift
- Sources/DeclarativeUIKit/ViewExtension/UIPickerView+.swift
> UIPickerView, UIDatePicker

- DeclarativeUIKitDemo/DeclarativeUIKitDemo/ProgressView/ProgressViewViewController.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/RootViewController.swift
- Documentation/en/index.md
- Documentation/en/uiprogressview.md
- Documentation/ja/index.md
- Documentation/ja/uiprogressview.md
- Sources/DeclarativeUIKit/ViewExtension/UIProgressView+.swift
> UIProgressView

- DeclarativeUIKitDemo/DeclarativeUIKitDemo/Simple/Simple3ViewController.swift
- Documentation/en/index.md
- Documentation/en/uicolorwell.md
- Documentation/en/uicontrol.md
- Documentation/ja/index.md
- Documentation/ja/uicolorwell.md
- Documentation/ja/uicontrol.md
- Sources/DeclarativeUIKit/ViewExtension/UIColorWell+.swift
- Sources/DeclarativeUIKit/ViewExtension/UIControl+.swift
> uicolorwell

- DeclarativeUIKitDemo/DeclarativeUIKitDemo.xcodeproj/project.pbxproj
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/RootViewController.swift
- DeclarativeUIKitDemo/DeclarativeUIKitDemo/VisualEffect/VisualEffectViewController.swift
- Documentation/en/index.md
- Documentation/en/uivisualeffectview.md
- Documentation/ja/index.md
- Documentation/ja/uivisualeffectview.md
- Sources/DeclarativeUIKit/ViewExtension/UIVisualEffectView+.swift
> visual effect
